
# Terminal Font
font_family JetBrainsMonoNL NF
font_size 11

# Visible
background_opacity 0.65

# Mouse Dragging
mouse_map left click ungrabbed mouse_selection normal
mouse_map left doubleclick ungrabbed mouse_selection word
mouse_map left tripleclick ungrabbed mouse_selection line

# Copy & Paste
copy_on_select yes

# Sound Options
enable_audio_bell no

# BEGIN_KITTY_THEME
# Base4Tone_Modern_W Dark
include current-theme.conf
# END_KITTY_THEME
